/**
 * Created by takaruz on 10/5/16.
 */
export const LOAD_CLIENTS_REQUEST = 'LOAD_CLIENTS_REQUEST'
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS'
export const LOAD_CLIENTS_FAILURE = 'LOAD_CLIENTS_FAILURE'

export const LOAD_APPS_REQUEST = 'LOAD_APPS_REQUEST'
export const LOAD_APPS_SUCCESS = 'LOAD_APPS_SUCCESS'
export const LOAD_APPS_FAILURE = 'LOAD_APPS_FAILURE'

export const LOAD_VERSION_REQUEST = 'LOAD_VERSION_REQUEST'
export const LOAD_VERSION_SUCCESS = 'LOAD_VERSION_SUCCESS'
export const LOAD_VERSION_FAILURE = 'LOAD_VERSION_FAILURE'

export const SELECT_APP     = 'SELECT_APP'
export const SELECT_CLIENT  = 'SELECT_CLIENT'
export const SELECT_VERSION = 'SELECT_VERSION'

export const INIT_APP     = 'INIT_APP'
export const INIT_CLIENT  = 'INIT_CLIENT'
export const INIT_VERSION = 'INIT_VERSION'
